/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HourlyPnlRouteImport } from './routes/hourly-pnl'
import { Route as LossStreaksRouteImport } from './routes/loss-streaks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StreakTimingsRouteImport } from './routes/streak-timings'
import { Route as PatternHeatmapRouteImport } from './routes/pattern/heatmap'
import { Route as PatternHotColdRouteImport } from './routes/pattern/hot-cold'
import { Route as PatternRecoveryRouteImport } from './routes/pattern/recovery'
import { Route as PatternSequencesRouteImport } from './routes/pattern/sequences'
import { Route as PatternWinStreaksRouteImport } from './routes/pattern/win-streaks'
import { Route as PatternWindowCompareRouteImport } from './routes/pattern/window-compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HourlyPnlRoute = HourlyPnlRouteImport.update({
  id: '/hourly-pnl',
  path: '/hourly-pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const LossStreaksRoute = LossStreaksRouteImport.update({
  id: '/loss-streaks',
  path: '/loss-streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakTimingsRoute = StreakTimingsRouteImport.update({
  id: '/streak-timings',
  path: '/streak-timings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternHeatmapRoute = PatternHeatmapRouteImport.update({
  id: '/pattern/heatmap',
  path: '/pattern/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternHotColdRoute = PatternHotColdRouteImport.update({
  id: '/pattern/hot-cold',
  path: '/pattern/hot-cold',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternRecoveryRoute = PatternRecoveryRouteImport.update({
  id: '/pattern/recovery',
  path: '/pattern/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternSequencesRoute = PatternSequencesRouteImport.update({
  id: '/pattern/sequences',
  path: '/pattern/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternWinStreaksRoute = PatternWinStreaksRouteImport.update({
  id: '/pattern/win-streaks',
  path: '/pattern/win-streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternWindowCompareRoute = PatternWindowCompareRouteImport.update({
  id: '/pattern/window-compare',
  path: '/pattern/window-compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/hourly-pnl': typeof HourlyPnlRoute
  '/loss-streaks': typeof LossStreaksRoute
  '/settings': typeof SettingsRoute
  '/streak-timings': typeof StreakTimingsRoute
  '/pattern/heatmap': typeof PatternHeatmapRoute
  '/pattern/hot-cold': typeof PatternHotColdRoute
  '/pattern/recovery': typeof PatternRecoveryRoute
  '/pattern/sequences': typeof PatternSequencesRoute
  '/pattern/win-streaks': typeof PatternWinStreaksRoute
  '/pattern/window-compare': typeof PatternWindowCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/hourly-pnl': typeof HourlyPnlRoute
  '/loss-streaks': typeof LossStreaksRoute
  '/settings': typeof SettingsRoute
  '/streak-timings': typeof StreakTimingsRoute
  '/pattern/heatmap': typeof PatternHeatmapRoute
  '/pattern/hot-cold': typeof PatternHotColdRoute
  '/pattern/recovery': typeof PatternRecoveryRoute
  '/pattern/sequences': typeof PatternSequencesRoute
  '/pattern/win-streaks': typeof PatternWinStreaksRoute
  '/pattern/window-compare': typeof PatternWindowCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/hourly-pnl': typeof HourlyPnlRoute
  '/loss-streaks': typeof LossStreaksRoute
  '/settings': typeof SettingsRoute
  '/streak-timings': typeof StreakTimingsRoute
  '/pattern/heatmap': typeof PatternHeatmapRoute
  '/pattern/hot-cold': typeof PatternHotColdRoute
  '/pattern/recovery': typeof PatternRecoveryRoute
  '/pattern/sequences': typeof PatternSequencesRoute
  '/pattern/win-streaks': typeof PatternWinStreaksRoute
  '/pattern/window-compare': typeof PatternWindowCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/history'
    | '/hourly-pnl'
    | '/loss-streaks'
    | '/settings'
    | '/streak-timings'
    | '/pattern/heatmap'
    | '/pattern/hot-cold'
    | '/pattern/recovery'
    | '/pattern/sequences'
    | '/pattern/win-streaks'
    | '/pattern/window-compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/history'
    | '/hourly-pnl'
    | '/loss-streaks'
    | '/settings'
    | '/streak-timings'
    | '/pattern/heatmap'
    | '/pattern/hot-cold'
    | '/pattern/recovery'
    | '/pattern/sequences'
    | '/pattern/win-streaks'
    | '/pattern/window-compare'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/history'
    | '/hourly-pnl'
    | '/loss-streaks'
    | '/settings'
    | '/streak-timings'
    | '/pattern/heatmap'
    | '/pattern/hot-cold'
    | '/pattern/recovery'
    | '/pattern/sequences'
    | '/pattern/win-streaks'
    | '/pattern/window-compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HistoryRoute: typeof HistoryRoute
  HourlyPnlRoute: typeof HourlyPnlRoute
  LossStreaksRoute: typeof LossStreaksRoute
  SettingsRoute: typeof SettingsRoute
  StreakTimingsRoute: typeof StreakTimingsRoute
  PatternHeatmapRoute: typeof PatternHeatmapRoute
  PatternHotColdRoute: typeof PatternHotColdRoute
  PatternRecoveryRoute: typeof PatternRecoveryRoute
  PatternSequencesRoute: typeof PatternSequencesRoute
  PatternWinStreaksRoute: typeof PatternWinStreaksRoute
  PatternWindowCompareRoute: typeof PatternWindowCompareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hourly-pnl': {
      id: '/hourly-pnl'
      path: '/hourly-pnl'
      fullPath: '/hourly-pnl'
      preLoaderRoute: typeof HourlyPnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loss-streaks': {
      id: '/loss-streaks'
      path: '/loss-streaks'
      fullPath: '/loss-streaks'
      preLoaderRoute: typeof LossStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak-timings': {
      id: '/streak-timings'
      path: '/streak-timings'
      fullPath: '/streak-timings'
      preLoaderRoute: typeof StreakTimingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/heatmap': {
      id: '/pattern/heatmap'
      path: '/pattern/heatmap'
      fullPath: '/pattern/heatmap'
      preLoaderRoute: typeof PatternHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/hot-cold': {
      id: '/pattern/hot-cold'
      path: '/pattern/hot-cold'
      fullPath: '/pattern/hot-cold'
      preLoaderRoute: typeof PatternHotColdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/recovery': {
      id: '/pattern/recovery'
      path: '/pattern/recovery'
      fullPath: '/pattern/recovery'
      preLoaderRoute: typeof PatternRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/sequences': {
      id: '/pattern/sequences'
      path: '/pattern/sequences'
      fullPath: '/pattern/sequences'
      preLoaderRoute: typeof PatternSequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/win-streaks': {
      id: '/pattern/win-streaks'
      path: '/pattern/win-streaks'
      fullPath: '/pattern/win-streaks'
      preLoaderRoute: typeof PatternWinStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/window-compare': {
      id: '/pattern/window-compare'
      path: '/pattern/window-compare'
      fullPath: '/pattern/window-compare'
      preLoaderRoute: typeof PatternWindowCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  HistoryRoute: HistoryRoute,
  HourlyPnlRoute: HourlyPnlRoute,
  LossStreaksRoute: LossStreaksRoute,
  SettingsRoute: SettingsRoute,
  StreakTimingsRoute: StreakTimingsRoute,
  PatternHeatmapRoute: PatternHeatmapRoute,
  PatternHotColdRoute: PatternHotColdRoute,
  PatternRecoveryRoute: PatternRecoveryRoute,
  PatternSequencesRoute: PatternSequencesRoute,
  PatternWinStreaksRoute: PatternWinStreaksRoute,
  PatternWindowCompareRoute: PatternWindowCompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
